# Checking enviroment states and action sets

In [15]:
import sys
import os.path
sys.path.append("..")
from A3C_Agent import *
from ENV_DETAILS import *

In [16]:
if os.name == 'nt':
    main_hyper_dir = "D:\\Artificial_Intelligence\\Portfolio\\RL_updated\\LunarLander\\" # Windows
    conda_python_exec = 'C:\\Users\\yanie\\anaconda3\\envs\\ai_dev\\python.exe '# Windows
    logs_dir = main_hyper_dir+'Hyperparam_tuning\\' # Windows
else:
    main_hyper_dir = "/media/n/NewDisk/Artificial_Intelligence/Portfolio/RL_updated/LunarLander/" # Linux
    conda_python_exec = '/home/n/anaconda3/envs/ai_dev/bin/python '# Linux
    logs_dir = main_hyper_dir+'Hyperparam_tuning_a3c/' # Linux

ENV = "LunarLander-v2"
SUCESS_CRITERIA_VALUE = ENV_DETAILS[ENV]["SUCESS_CRITERIA_VALUE"]
SUCESS_CRITERIA_EPOCH = ENV_DETAILS[ENV]["SUCESS_CRITERIA_EPOCH"]
EPISODES = ENV_DETAILS[ENV]["EPISODES"]

In [17]:

env = gym.make(ENV)
env


<TimeLimit<OrderEnforcing<PassiveEnvChecker<LunarLander<LunarLander-v2>>>>>

In [18]:
s = env.observation_space.sample()
s

array([-0.13725457,  1.046495  ,  1.6977865 , -2.3692205 , -1.0841154 ,
       -2.9228    ,  0.90587187,  0.67300284], dtype=float32)

In [19]:
env.observation_space, env.observation_space.shape

(Box([-1.5       -1.5       -5.        -5.        -3.1415927 -5.
  -0.        -0.       ], [1.5       1.5       5.        5.        3.1415927 5.        1.
  1.       ], (8,), float32),
 (8,))

In [20]:
s = env.reset()
s[0]

array([ 0.00345535,  1.4060721 ,  0.3499771 , -0.21547431, -0.00399713,
       -0.07927497,  0.        ,  0.        ], dtype=float32)

In [21]:
s = env.reset()[0]
env.action_space.n, env.action_space, env.step(1)

(4,
 Discrete(4),
 (array([-0.00464497,  1.4085038 , -0.24120267, -0.06632995,  0.00734536,
          0.09393398,  0.        ,  0.        ], dtype=float32),
  -1.90531853937773,
  False,
  False,
  {}))

# Advantage Asynch Actor-Critic 

This time we will implement the A3C not considering Actor and Critic as part of the same network

### Training/Hyperparam run

In [22]:
%tensorboard --logdir logs_general/hyper

UsageError: Line magic function `%tensorboard` not found.


In [23]:
TUNING_TYPE = "BAYES"
HYPERPARAM_TUNING = True
writer= "Training/fit_A3C/"

if TUNING_TYPE == "MANUAL":
    params = {}
    params["n_enviroment"] =[20]
    params["discount"] =[0.96, 0.97]
    params["end_of_episode"] = [400]
    params["learning_rate"] = [0.001]
    params["entropy_factor"] = [ 0.01, 0.05]
    params["epsilon"] = [1]
    params["boltzman_factor"] = [1]
    params["exploration_technique"] = ['soft', 'epsilon']
    params["training_steps"] = [3000000]
    params["dense_units"] = [32, 128]
    params["time_to_update"] = [400]
    params["use_LSTM"] =[False]


    hyperparam_combination = list(itertools.product(*list(params.values())))
    

    try:

        files = [name for name in os.listdir(logs_dir) if os.path.isfile(os.path.join(logs_dir, name)) and name != "logfile.txt" and name != "merged_results.json"]
        if len(files) >= 1: merge_JsonFiles(main_hyper_dir, logs_dir, files)

        res_file = logs_dir+"merged_results.json"
        def without_keys(d, keys):
            return {x: d[x] for x in d if x not in keys}


        if os.path.isfile(res_file):
            with open(res_file, 'r') as f:
                complete_file = json.load(f)

            newlist = sorted(complete_file, key=lambda d: d['mean_rewards'], reverse=True) 
            params = []
            for i, f in enumerate(newlist):
                label = "disc : "+str(f['discount'])+" | "+"lr : "+str(f['learning_rate'])+" | "+"entropy : "+str(f['entropy_factor'])+" | "+"update : "+str(f['time_to_update'])
                plt.figure(figsize=[35,4])
                plt.plot(f['rewards'], label = label)
                plt.legend()
                max_mean_reward = f['mean_rewards']
                params.append(f)
                print(without_keys(f,"rewards"))
                if i == 10:
                    break
            plt.title("Evaluation rewards"); plt.grid();
            plt.show()

    except:
        pass



In [24]:
if HYPERPARAM_TUNING:

    dir = r"Hyperparam_kt_A3C"
    project_name = "keras_tunning_soft"

    tuner = kt.BayesianOptimization(
            MyHyperModel(hyper_dir = dir+"/"+project_name,  writer = "logs_hyper/A3C_soft/", 
                          end_of_episode = EPISODES, n_enviroment = 5, 
                  evaluation_epoch = 2000, training_steps = 600000,
                  sucess_criteria_epochs = SUCESS_CRITERIA_EPOCH, sucess_criteria_value= SUCESS_CRITERIA_VALUE,
                  discount_min = 0.90, discount_max = 0.99,
                  entropy_min = 0.0001, entropy_max = 0.05,
                  lr_min = 0.00001, lr_max = 0.005,
                  dense_min = 32, dense_max = 500,
                  lstm_min = 32, lstm_max = 128,
                  time_to_update_min = 100, time_to_update_max=600,
                  environment_name=ENV),
            objective= kt.Objective('total_train_reward', direction="max"), 
            max_trials = 40,
            # distribution_strategy= strategy,
            directory=dir,
            project_name=project_name
        )
    tuner.search(x=[0], y=[1])
    
    # project_name = "keras_tunning_epsilon"
    # tuner = kt.BayesianOptimization(
    #         MyHyperModel(hyper_dir = dir+"/"+project_name,  writer = "logs_hyper/A3C_epsilon/", exploration_tech = "epsilon"),
    #         objective= kt.Objective('total_train_reward', direction="max"), 
    #         max_trials = 50,
    #         # distribution_strategy= strategy,
    #         directory=dir,
    #         project_name=project_name
    #     )
    # tuner.search(x=[0], y=[1])

    # project_name = "keras_tunning_boltzman"
    # tuner = kt.BayesianOptimization(
    #         MyHyperModel(hyper_dir = dir+"/"+project_name,  writer = "logs_hyper/A3C_boltzman/", exploration_tech = "boltzman"),
    #         objective= kt.Objective('total_train_reward', direction="max"), 
    #         max_trials = 50,
    #         # distribution_strategy= strategy,
    #         directory=dir,
    #         project_name=project_name
    #     )
    # tuner.search(x=[0], y=[1])

    # dir = r"Hyperparam_kt_A3C_LSTM"
    # project_name = "keras_tunning_soft"
    # tuner_lstm = kt.BayesianOptimization(
    #         MyHyperModel(hyper_dir = dir+"/"+project_name, writer = "logs_A3C_LSTM/A3C_soft/" ,use_LSTM = True),
    #         objective= kt.Objective('total_train_reward', direction="max"), 
    #         max_trials = 40,
    #         # distribution_strategy= strategy,
    #         directory=dir,
    #         project_name='keras_tunning'
    #     )
    # tuner_lstm.search(x=[0], y=[1])

    # project_name = "keras_tunning_epsilon"
    # tuner_lstm = kt.BayesianOptimization(
    #         MyHyperModel(hyper_dir = dir+"/"+project_name, writer = "logs_A3C_LSTM/A3C_epsilon/" ,use_LSTM = True, exploration_tech = "epsilon"),
    #         objective= kt.Objective('total_train_reward', direction="max"), 
    #         max_trials = 40,
    #         # distribution_strategy= strategy,
    #         directory=dir,
    #         project_name='keras_tunning'
    #     )
    # tuner_lstm.search(x=[0], y=[1])

    # project_name = "keras_tunning_boltzman"
    # tuner_lstm = kt.BayesianOptimization(
    #         MyHyperModel(hyper_dir = dir+"/"+project_name, writer = "logs_A3C_LSTM/A3C_boltzman/" ,use_LSTM = True, exploration_tech = "boltzman"),
    #         objective= kt.Objective('total_train_reward', direction="max"), 
    #         max_trials = 40,
    #         # distribution_strategy= strategy,
    #         directory=dir,
    #         project_name='keras_tunning'
    #     )
    # tuner_lstm.search(x=[0], y=[1])
   
else : 
    
    for exploration_tech in ['boltzman', 'epsilon']:
        print("Acquiring parameters ....")
        writer= "Training/fit_A3C/"

        n_enviroment = 10
        training_steps = 1000000
        learning_rate= 0.001
        entropy_factor = 0.1
        discount = 0.99
        dense_units = 512
        lstm_units = 128
        time_to_update= 100
        end_of_episode = 300
        use_LSTM = False

        
        run_training(training_steps, learning_rate, entropy_factor, exploration_tech, discount, time_to_update, dense_units, lstm_units, n_enviroment, writer, use_LSTM, end_of_episode, environment_name = "LunarLander-v2")
            

Trial 35 Complete [01h 36m 17s]
total_train_reward: 155.28341060132752

Best total_train_reward So Far: 256.9092418548197
Total elapsed time: 07h 07m 09s

Search: Running Trial #36

Value             |Best Value So Far |Hyperparameter
0.99              |0.99              |discount
0.049146          |0.027255          |entropy_factor
0.0040571         |0.0012834         |learning_rate
472               |162               |dense_units

Trial number :  36
Epoch: 2000 : Reward eval/Train: -776.1193574437958/-427.60788489459634 | epsilon : 1
Epoch: 4000 : Reward eval/Train: -984.2079880481681/-1847.1211064787399 | epsilon : 1
Epoch: 6000 : Reward eval/Train: -957.3014406315106/-618.5742916047288 | epsilon : 1
Epoch: 8000 : Reward eval/Train: -728.3624438273151/-519.4282390801923 | epsilon : 1
Epoch: 10000 : Reward eval/Train: -765.6866608673913/-728.456161183091 | epsilon : 1
Epoch: 12000 : Reward eval/Train: -1571.5876951016671/-569.5907977323143 | epsilon : 1
Epoch: 14000 : Reward eval/Tr

In [ ]:

exploration_tech = "soft"

hyperparam_combination=[]
for trials in tuner.oracle.get_best_trials(num_trials=3):
    print(f"Trial id :{trials.trial_id} | Score :{trials.score} -->",trials.hyperparameters.values)

    n_env = 30
    end_ep = 1000
    ep = 1
    bolt_fact = 1
    train_steps = 5000000
    disc = trials.hyperparameters.values["discount"]
    lr = trials.hyperparameters.values["learning_rate"]
    entropy_fact = trials.hyperparameters.values["entropy_factor"]
    d = trials.hyperparameters.values["dense_units"]
    time_to_update = 100 if exploration_tech == "soft" else trials.hyperparameters.values["time_to_update"]
    ulstm = False

    hyperparam_combination.append((n_env, disc, end_ep, lr, entropy_fact, ep, bolt_fact, exploration_tech, train_steps, d, time_to_update, ulstm))

Trial id :23 | Score :256.9092418548197 --> {'discount': 0.99, 'entropy_factor': 0.02725512838544938, 'learning_rate': 0.0012833657996505648, 'dense_units': 162}
Trial id :07 | Score :255.4684100390277 --> {'discount': 0.99, 'entropy_factor': 0.04058888538676041, 'learning_rate': 0.00095066954602934, 'dense_units': 372}
Trial id :28 | Score :251.59047128674828 --> {'discount': 0.99, 'entropy_factor': 0.023885694097790046, 'learning_rate': 0.002973449264458015, 'dense_units': 193}


In [ ]:
len(hyperparam_combination), hyperparam_combination

(3,
 [(30,
   0.99,
   1000,
   0.0012833657996505648,
   0.02725512838544938,
   1,
   1,
   'soft',
   5000000,
   162,
   100,
   False),
  (30,
   0.99,
   1000,
   0.00095066954602934,
   0.04058888538676041,
   1,
   1,
   'soft',
   5000000,
   372,
   100,
   False),
  (30,
   0.99,
   1000,
   0.002973449264458015,
   0.023885694097790046,
   1,
   1,
   'soft',
   5000000,
   193,
   100,
   False)])

In [ ]:
# run_hyperparam(TUNING_TYPE= "MANUAL", TUNING_TYPE = TUNING_TYPE, hyperparam_combination = hyperparam_combination,  total_files = 4)

In [ ]:

val_env = gym.make(ENV, render_mode = "rgb_array")
dir = r"Hyperparam_kt_A3C"

for exploration_tech in ["soft" ,"epsilon", "boltzman"]:

    project_name = "keras_tunning_"+exploration_tech

    tuner = kt.BayesianOptimization(
            MyHyperModel( hyper_dir = dir+"/"+project_name,  writer = "logs_hyper/A3C_"+exploration_tech+"/", exploration_tech =exploration_tech, 
                          end_of_episode = EPISODES, n_enviroment = 5, 
                  evaluation_epoch = 2000, training_steps = 600000,
                  sucess_criteria_epochs = SUCESS_CRITERIA_EPOCH, sucess_criteria_value= SUCESS_CRITERIA_VALUE,
                  discount_min = 0.90, discount_max = 0.99,
                  entropy_min = 0.0001, entropy_max = 0.05,
                  lr_min = 0.00001, lr_max = 0.005,
                  dense_min = 32, dense_max = 500,
                  lstm_min = 32, lstm_max = 128,
                  time_to_update_min = 100, time_to_update_max=600,
                  environment_name=ENV),
            objective= kt.Objective('total_train_reward', direction="max"), 
            max_trials = 40,
            # distribution_strategy= strategy,
            directory=dir,
            project_name=project_name
        )

    for trials in tuner.oracle.get_best_trials(num_trials=1):
        print(f"Trial id :{trials.trial_id} | Score :{trials.score} -->",trials.hyperparameters.values)
        

    env_model = tuner.get_best_models()[0]
    final_rewards = final_evaluation(env_model,val_env,n_tries=200, exploration=exploration_tech,  video_name = "./A3C_"+exploration_tech+"_video.mp4")
    print("Final mean reward '",exploration_tech,"':", np.mean(final_rewards))

    

INFO:tensorflow:Reloading Tuner from Hyperparam_kt_A3C/keras_tunning_soft/tuner0.json
Trial id :23 | Score :256.9092418548197 --> {'discount': 0.99, 'entropy_factor': 0.02725512838544938, 'learning_rate': 0.0012833657996505648, 'dense_units': 162}
Trial number :  30
Moviepy - Building video ./A3C_soft_video.mp4.
Moviepy - Writing video ./A3C_soft_video.mp4



Moviepy - Done !
Moviepy - video ready ./A3C_soft_video.mp4
Final mean reward ' soft ': 251.18667792553265
INFO:tensorflow:Reloading Tuner from Hyperparam_kt_A3C/keras_tunning_epsilon/tuner0.json
Trial id :21 | Score :243.8703166088034 --> {'discount': 0.99, 'entropy_factor': 0.05, 'learning_rate': 0.005, 'dense_units': 500, 'time_to_update': 500}
Trial number :  26
Moviepy - Building video ./A3C_epsilon_video.mp4.
Moviepy - Writing video ./A3C_epsilon_video.mp4



Moviepy - Done !
Moviepy - video ready ./A3C_epsilon_video.mp4
Final mean reward ' epsilon ': 236.6058385368619
INFO:tensorflow:Reloading Tuner from Hyperparam_kt_A3C/keras_tunning_boltzman/tuner0.json
Trial id :02 | Score :266.5749316351991 --> {'discount': 0.99, 'entropy_factor': 0.013874529377827684, 'learning_rate': 0.0007061589601898285, 'dense_units': 294, 'time_to_update': 300}
Trial number :  30
Moviepy - Building video ./A3C_boltzman_video.mp4.
Moviepy - Writing video ./A3C_boltzman_video.mp4



Moviepy - Done !
Moviepy - video ready ./A3C_boltzman_video.mp4
Final mean reward ' boltzman ': 220.153031865886
