# Checking enviroment states and action sets

In [1]:
import sys
import os.path
sys.path.append("..")
from SAC_Agent_lighter import *
from ENV_DETAILS import *
import os

2024-01-31 14:45:30.401127: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-31 14:45:30.453669: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-01-31 14:45:30.469887: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-31 14:45:30.739701: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: li

Num devices available:  [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


2024-01-31 14:45:31.482680: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-01-31 14:45:31.521594: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-01-31 14:45:31.521791: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero


In [2]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 465837574687195066
xla_global_id: -1
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 22126723072
locality {
  bus_id: 1
  links {
  }
}
incarnation: 14327526734389593950
physical_device_desc: "device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:01:00.0, compute capability: 8.6"
xla_global_id: 416903419
]


2024-01-31 14:45:31.526206: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-31 14:45:31.528201: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-01-31 14:45:31.528361: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-01-31 14:45:31.528450: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA

In [3]:
if os.name == 'nt':
    main_hyper_dir = "D:\\Artificial_Intelligence\\Portfolio\\RL_updated\\BipedalWalker\\" # Windows
    conda_python_exec = 'C:\\Users\\yanie\\anaconda3\\envs\\ai_dev\\python.exe '# Windows
    logs_dir = main_hyper_dir+'Hyperparam_tuning\\' # Windows
else:
    main_hyper_dir = "/media/n/NewDisk/Artificial_Intelligence/Portfolio/RL_updated/BipedalWalker/" # Linux
    conda_python_exec = '/home/n/anaconda3/envs/ai_dev/bin/python '# Linux
    logs_dir = main_hyper_dir+'Hyperparam_tuning_sac/' # Linux

ENV = "Ant-v2"
SUCESS_CRITERIA_VALUE = ENV_DETAILS[ENV]["SUCESS_CRITERIA_VALUE"]
SUCESS_CRITERIA_EPOCH = ENV_DETAILS[ENV]["SUCESS_CRITERIA_EPOCH"]
EPISODES = ENV_DETAILS[ENV]["EPISODES"]

In [4]:
#LD_LIBRARY_PATH=/usr/local/cuda-12.1/lib64:/usr/local/cuda/lib64:/usr/local/cuda-12.1/lib64:/usr/local/cuda/lib64:/usr/local/cuda-12.1/lib64:/usr/local/cuda/lib64/:/home/n/.mujoco/mujoco210/bin
! echo $LD_LIBRARY_PATHc

In [5]:
env = gym.make(ENV)
env


<TimeLimit<OrderEnforcing<AntEnv<Ant-v2>>>>

In [6]:

max_steps = env._max_episode_steps
max_steps

1000

In [7]:
s = env.observation_space.sample()
s

array([-0.02788014,  0.91035177,  0.20967906, -0.0720419 , -0.32335887,
        0.90686957,  0.60917188,  0.5674793 , -2.1603379 ,  0.42575909,
       -0.01914482, -1.61755756,  1.11122851,  0.47161049,  1.03820389,
        0.20490961,  0.58121653,  0.71221784, -0.07345233,  0.23685948,
        0.13920604, -0.17878874, -1.12668479,  0.08698594, -0.2752055 ,
        0.13237564,  1.75634035,  0.89875864, -0.07351353, -0.11734575,
        1.51271693, -2.46635561,  2.33806386,  0.8046801 ,  1.32152021,
        2.31560103,  0.8510059 ,  0.92317005, -1.07803514, -0.88115724,
       -0.06281868,  0.00651866, -0.04483359,  0.88863015,  0.4291408 ,
       -1.06639973,  0.21321705, -0.42909799,  1.00235032,  0.56356912,
        0.52576125, -0.73119533, -0.33070524, -1.0418612 ,  1.95401574,
       -0.74075554,  0.12844253,  0.1640146 , -1.99457588, -0.21482059,
       -0.07546758,  0.31561921,  0.46196963, -1.15908133,  0.93523707,
        1.47047761, -1.64464199,  0.39707663,  2.62483057, -1.81

In [8]:
env.observation_space

Box(-inf, inf, (111,), float64)

In [9]:
env.observation_space.shape

(111,)

In [10]:
s = env.reset()
s

array([ 0.69543072,  0.99452999,  0.01277502,  0.07992402, -0.06602305,
       -0.06009736, -0.07755146,  0.06102621, -0.06634228, -0.02153657,
       -0.0644069 , -0.02782276,  0.00381734,  0.09533074, -0.03377354,
        0.11534974, -0.03852704, -0.04068562, -0.07825016, -0.01942004,
       -0.12935553, -0.12430277, -0.08887245,  0.00476441, -0.12312941,
        0.07657353,  0.06161828,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [11]:
s = np.array(s).reshape((1, env.observation_space.shape[0]))
s

array([[ 0.69543072,  0.99452999,  0.01277502,  0.07992402, -0.06602305,
        -0.06009736, -0.07755146,  0.06102621, -0.06634228, -0.02153657,
        -0.0644069 , -0.02782276,  0.00381734,  0.09533074, -0.03377354,
         0.11534974, -0.03852704, -0.04068562, -0.07825016, -0.01942004,
        -0.12935553, -0.12430277, -0.08887245,  0.00476441, -0.12312941,
         0.07657353,  0.06161828,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0. 

In [12]:
a = env.action_space.sample()
a, a.shape, a.reshape((1, len(a))).shape

(array([-0.8328846 , -0.22468966, -0.27181223,  0.8705417 , -0.50300074,
         0.83511746, -0.06442186,  0.99286246], dtype=float32),
 (8,),
 (1, 8))

In [13]:
env.step(a)

(array([ 0.7211362 ,  0.99683716,  0.01859033,  0.06224911, -0.04577262,
        -0.11159353,  0.47433447, -0.03702742, -0.39403557, -0.03448048,
        -0.39023026, -0.17602663,  0.41031931,  0.28179652,  0.05261549,
         0.23736318,  0.51159411, -1.44186014,  1.70063541, -2.01996703,
        14.8392743 , -3.76309538, -4.98142221, -0.51754391, -4.6604206 ,
        -5.96320881,  8.31417629,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0. 

In [14]:
env.action_space.sample()

array([ 0.48457184,  0.80026186,  0.35995427,  0.54075885, -0.11127175,
        0.13630508, -0.32472062, -0.40596324], dtype=float32)

### Training/Hyperparam run

In [15]:
%tensorboard --logdir logs_general/hyper

UsageError: Line magic function `%tensorboard` not found.


In [16]:
TUNING_TYPE = "BAYES"
HYPERPARAM_TUNING = True
writer= "Training/fit_sac/"


In [17]:
if HYPERPARAM_TUNING:

    dir = r"Hyperparam_kt_sac"
    project_name = "keras_tunning_soft_lighter"

    tuner = kt.BayesianOptimization(
            MyHyperModel( hyper_dir = dir+"/"+project_name,  writer = "logs_hyper/sac_lighter/",
                        end_of_episode = EPISODES, evaluation_epoch = env._max_episode_steps, training_steps = 700000,
                sucess_criteria_epochs = SUCESS_CRITERIA_EPOCH, sucess_criteria_value= SUCESS_CRITERIA_VALUE,
                discount_min = 0.95, discount_max = 0.99,
                lr_actor_min = 0.000001, lr_actor_max = 0.005,
                lr_critic_1_min = 0.000001, lr_critic_1_max = 0.005,
                dense_min = 32, dense_max = 256,
                environment_name=ENV,
                tau_min = 0.001, tau_max = 0.1,
                reward_scaler = 1, num_layers_act = 2, num_layers_crit =2),
            objective= kt.Objective('total_train_reward', direction="max"), 
            max_trials = 30,
            # distribution_strategy= strategy,
            directory=dir,
            project_name=project_name
        )
    tuner.search(x=[0], y=[1])
else : 
    
        print("Acquiring parameters ....")
        writer= "Training/fit_sac_lighter/"

        training_steps = 1000000
        learning_rate= 0.001
        entropy_factor = 0.1
        discount = 0.99
        dense_units_actor = [128,64]
        num_layers_actor = 2
        dense_units_critic = [128,64]
        num_layers_crit = 2
        time_to_update= 100
        end_of_episode = 300
        tau = 0.01
        
        run_training(training_steps,  discount, dense_units_actor,  dense_units_critic, num_layers_actor, num_layers_crit, writer, end_of_episode,
                      environment_name = ENV,reward_scaler = 10, return_agent = False,lr_actor= 0.001, lr_critic_1= 0.001, lr_alpha = 0.001, tau = 0.001)
        

Trial number :  1

Search: Running Trial #1

Value             |Best Value So Far |Hyperparameter
0.0023173         |0.0023173         |lr_actor
0.0037699         |0.0037699         |lr_critic_1
0.00096906        |0.00096906        |lr_alpha
0.015557          |0.015557          |tau
1                 |1                 |n_dense_layers_actor
119               |119               |dense_units_act_0
2                 |2                 |n_dense_layers_critic
115               |115               |dense_units_crit_0

Trial number :  1
Epoch: 20000 | Memory size : 20001 | Reward eval/Train: -593.038146030264/-157.8569712513889 
Epoch: 40000 | Memory size : 40001 | Reward eval/Train: -236.440021584432/-129.40047489931126 
Epoch: 60000 | Memory size : 60001 | Reward eval/Train: -138.35078866790002/-90.02201592907589 
Epoch: 80000 | Memory size : 80001 | Reward eval/Train: -115.29683282834806/-78.46619485591381 
Epoch: 100000 | Memory size : 100000 | Reward eval/Train: -222.00176914074052/-140.8

In [ ]:
exploration_tech = "soft"
hyperparam_combination=[]
for trials in tuner.oracle.get_best_trials(num_trials=3):
    print(f"Trial id :{trials.trial_id} | Score :{trials.score} -->",trials.hyperparameters.values)

In [ ]:

val_env = gym.make(ENV)#, render_mode = "rgb_array"
dir = r"Hyperparam_kt_sac"

for trials in tuner.oracle.get_best_trials(num_trials=1):
    print(f"Trial id :{trials.trial_id} | Score :{trials.score} -->",trials.hyperparameters.values)
    
env_model = tuner.get_best_models()[0]
final_rewards = final_evaluation(env_model,val_env,n_tries=200, exploration=exploration_tech,  video_name = "./sac_"+exploration_tech+"_video.mp4")
print("Final mean reward '",exploration_tech,"':", np.mean(final_rewards))

In [ ]:
best_hp = tuner.get_best_hyperparameters()[0]
training_steps = 2000000
discount  = 0.99#best_hp["discount"]
lr_actor  = best_hp["lr_actor"]
lr_critic_1  = best_hp["lr_critic_1"]
tau  = best_hp["tau"]

end_of_episode = EPISODES
sucess_criteria_epochs = SUCESS_CRITERIA_EPOCH
sucess_criteria_value = SUCESS_CRITERIA_VALUE
save_factor=50000
return_agent = True
reward_scaler = 1
environment_name=ENV

n_dense_layers_actor = trials.hyperparameters.values["n_dense_layers_actor"]
dense_layers_actor = []
for i in range(n_dense_layers_actor):
    dense_layers_actor.append(trials.hyperparameters.values['dense_units_act_'+str(i)])

n_dense_layers_critic = trials.hyperparameters.values["n_dense_layers_critic"]
dense_layers_critic = []
for i in range(n_dense_layers_critic):
    dense_layers_critic.append(trials.hyperparameters.values['dense_units_crit_'+str(i)])

env_model = run_training(training_steps = training_steps,
                         discount = discount,  
                         dense_units_act = dense_layers_actor,  
                         dense_units_crit = dense_layers_critic, 
                         num_layer_a = n_dense_layers_actor, 
                         num_layer_c = n_dense_layers_critic, 
                         writer = writer, 
                         end_of_episode = end_of_episode, 
                         save_factor = save_factor, 
                         sucess_criteria_epochs = sucess_criteria_epochs , 
                         sucess_criteria_value = sucess_criteria_value, 
                         environment_name = environment_name, 
                         reward_scaler = reward_scaler , 
                         return_agent = return_agent,
                         lr_actor = lr_actor, 
                         lr_critic_1 = lr_critic_1, 
                         tau = tau )

In [ ]:
final_rewards = final_evaluation(env_model,val_env,n_tries=200, exploration=exploration_tech,  video_name = "./sac_lighter_"+exploration_tech+"_video.mp4")
